/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const project_Logic = require('./code/project-logic');

class cdaydemoSrv extends LCAPApplicationService {
    async init() {

        this.on('READ', 'Project', async (request, next) => {
            await project_Logic(request);
            return next();
        });

        return super.init();
    }
}


module.exports = {
    cdaydemoSrv
};